### ISSUE TITLE
Missing Library Files

### ISSUE THREAD

**Issue by dgadelha** [zf5/android_vendor_asus_a500cg#1]
Some library files are missing, which affects the Hardware keys on AOSP and possibly the Intel MultiDisplay Service on CyanogenMod.
Here is a list of the missing files on system/lib that are present on https://github.com/quanganh2627/android_vendor_asus_a500cg
I'll be checking those files and adding some of them soon, if required
```
lib/libAFE.so
lib/libBaiduMapSDK_v2_4_1.so
lib/libGLESv3.so
lib/libPdfConverter.so
lib/libSTC.so
lib/libcctapi.so
lib/libcurve25519-old.so
lib/libdrm.so
lib/libfilterpack_facedetect.so
lib/libinput.so
lib/libjSebring.so
lib/libjUPnPCP.so
lib/libjni_xt9input.so
lib/libkeyboard_jni.so
lib/libmllite.so
lib/libmorpho_panorama_gp.so
lib/libmplmpu.so
lib/libmultidisplay.so
lib/libmultidisplayjni.so
lib/libnatnl-1.7.11.2.so
lib/libola.so
lib/libreference-ril.so
lib/libsarcsoft_gallery.so
lib/libsarcsoftface.so
lib/libsmartdialer_oem_module.so
lib/libsmartdialernet_oem_module.so
lib/libsphere.so
lib/libsphere2.so
lib/libsphere3.so
lib/libstagefright_omx.so
lib/libstagefright_soft_aacdec.so
lib/libstagefright_soft_aacdec_mdp.so
lib/libstagefright_soft_aacenc.so
lib/libstagefright_soft_aacenc_mdp.so
lib/libstagefright_soft_alacdec.so
lib/libstagefright_soft_amrdec.so
lib/libstagefright_soft_amrdec_mdp.so
lib/libstagefright_soft_amrenc_mdp.so
lib/libstagefright_soft_amrnbenc.so
lib/libstagefright_soft_amrwbenc.so
lib/libstagefright_soft_mp3dec.so
lib/libstagefright_soft_mp3dec_mdp.so
lib/libstagefright_soft_vorbisdec_mdp.so
lib/libstagefright_soft_wmadec_mdp.so
lib/libstagefright_usbd.so
lib/libstlport_shared.so
lib/libstrokenumjni.so
lib/libsvml.so
lib/libtrendmicro_jni.so
lib/libutils.so
lib/libwatchdogd_devel.so
lib/soundfx/libaudiopreprocessing.so
lib/soundfx/libbundlewrapper.so
lib/soundfx/libdownmix.so
lib/soundfx/libeffectproxy.so
lib/soundfx/libldnhncr.so
lib/soundfx/liblpepreprocessing.so
lib/soundfx/libreverbwrapper.so
lib/soundfx/libvisualizer.so
```

A complete list of missing files is here:
[missing.txt](https://github.com/zf5/android_vendor_asus_a500cg/files/181140/missing.txt)

**Comment by dgadelha** [comment]
I've just compared this list with my built CyanogenMod and AOSP and just found that the real missing libs are these:
```
lib/libAFE.so
lib/libBaiduMapSDK_v2_4_1.so
lib/libPdfConverter.so
lib/libSTC.so
lib/libcctapi.so
lib/libcurve25519-old.so
lib/libfilterpack_facedetect.so
lib/libjSebring.so
lib/libjUPnPCP.so
lib/libjni_xt9input.so
lib/libkeyboard_jni.so
lib/libmllite.so
lib/libmorpho_panorama_gp.so
lib/libmplmpu.so
lib/libnatnl-1.7.11.2.so
lib/libola.so
lib/libsarcsoft_gallery.so
lib/libsarcsoftface.so
lib/libsmartdialer_oem_module.so
lib/libsmartdialernet_oem_module.so
lib/libsphere.so
lib/libsphere2.so
lib/libsphere3.so
lib/libstagefright_soft_aacdec_mdp.so
lib/libstagefright_soft_aacenc_mdp.so
lib/libstagefright_soft_alacdec.so
lib/libstagefright_soft_amrdec_mdp.so
lib/libstagefright_soft_amrenc_mdp.so
lib/libstagefright_soft_mp3dec_mdp.so
lib/libstagefright_soft_vorbisdec_mdp.so
lib/libstagefright_soft_wmadec_mdp.so
lib/libstagefright_usbd.so
lib/libstlport_shared.so
lib/libstrokenumjni.so
lib/libsvml.so
lib/libtrendmicro_jni.so
lib/libwatchdogd_devel.so
```
On AOSP also, this other lib was missing (which really doesn't matter):
```
lib/soundfx/liblpepreprocessing.so
```

**Comment by dgadelha** [comment]
Library | Description | Needed?|Notes
----------|---------------|-------------|-------
libAFE.so | AnyFirewallEngine | No | *N/A*
libBaiduMapSDK_v2_4_1.so | Baidu Map SDK | No | *N/A*
libPdfConverter.so | Jpeg2PDF Engine | No | *N/A*
libSTC.so | Intel (?) | (?) | It's some library from Intel that appears to work with Wi-Fi, mDNS, Bluetooth, Cloud, XML, IPC, ... **needs to be analyzed**
libcctapi.so | ASUS (?) | (?) | Works with Kernel, BIOS and has some Qualcomm code (`_Z15genLUT_QualcommPdPA3_iPcS2_`)
libcurve25519-old.so | WhisperSystems TextSecure Crypto Curve25519 | No | *N/A*
libfilterpack_facedetect.so | Filter Pack for Face Detection | Yes | (ASUS Camera) Provides Face Region Mask and Multi Face Detector
libjSebring.so | AwoX S.A. Java Sebring Library | Yes | Manages WiDi for DisplayManagerService (maybe the reason of locks and unlocks?)
libjUPnPCP.so | AwoX S.A. Java UPnPCP Library | Yes | Manages UPnP and DLNA
libjni_xt9input.so | XT9 Keyboard JNI | No | (ASUS Keyboard) XT9 V09.09.14.02^@3.41^@T9WRITE CJK V07.02.03.00 **Should be shipped with the APK**
libkeyboard_jni.so | ASUS Keyboard JNI for TouchpadService | No | **Should be shipped with the APK**
libmllite.so | Intel Redhookbay Gyroscope Calibration Library | Yes | *N/A*
libmorpho_panorama_gp.so | Morpho Inc.'s Morpho Panorama | Yes | (ASUS Camera) Panorama
libmplmpu.so | Accelerator / Gyroscope-related Library | Yes | *N/A*
libnatnl-1.7.11.2.so | ASUS NATNL (?) JNI | (?) | Appears to manage calls (yes, calls) and DTMF/STUN **maybe for ASUS Dialer?**
libola.so | Intel Panorama OLA Bitmap (Clovertrail-specific) | Yes | (ASUS Camera) Provides JPG compression for Panorama images (+ Face Detection?)
libsarcsoft_gallery.so | ArcSoft Inc. Gallery JNI Library | (**No**?) | (ASUS Gallery?) Provides Image Editing / Processing Tools
libsarcsoftface.so | ArcSoft Inc. Gallery FaceDetector JNI Library | (**No**?) | (ASUS Gallery?) Provides Face Detection for Gallery Pictures
libsmartdialer_oem_module.so | Cootek SmartDialer JNI Library | No | (ASUS Dialer/Contacts) Appears to provide some type of Contacts Search + work with SMS
libsmartdialernet_oem_module.so | Cootek SmartDialer Networking JNI Library | No | (ASUS Dialer/Contacts) Uploads your Call History (really?) `Java_com_cootek_smartdialer_net_NetEngine_uploadCallHistory` `Java_com_cootek_smartdialer_net_NetEngine_uploadCallLog`
libsphere.so<br>libsphere2.so<br>libsphere3.so | ASUS FeatureSphere JNI Library | (?) | (ASUS Camera) Image Processing ([Homepage?](https://www2.cisl.ucar.edu/resources/legacy/spherepack))
libstagefright_soft_aacdec_mdp.so<br>libstagefright_soft_aacenc_mdp.so<br>libstagefright_soft_alacdec.so<br>libstagefright_soft_amrdec_mdp.so<br>libstagefright_soft_amrenc_mdp.so<br>libstagefright_soft_mp3dec_mdp.so<br>libstagefright_soft_vorbisdec_mdp.so<br>libstagefright_soft_wmadec_mdp.so<br>libstagefright_usbd.so | StageFright Software Decoding/Encoding Libraries | (?) | (Encoding/Decoding works without these)
libstlport_shared.so | STLPort Shared Library | (**No**?) | *Maybe we need to build this instead of using a prebuilt*
libstrokenumjni.so | ASUS Contacts Character Stroke (for CN?) | (**No**?) | (ASUS Dialer/Contacts) Maybe this isn't needed
libsvml.so | Intel Short Vector Math Library | (**No**?) | *Maybe we need to build this instead of using a prebuilt* (also, what app uses it? - TODO)
libtrendmicro_jni.so | TrendMicro URL Check JNI Library for ASUS Browser | No | (ASUS Browser) Checks for URL safety via `asusbrowser10-sc.url.trendmicro.com`
libwatchdogd_devel.so | (?) | (?) | *N/A*
soundfx/liblpepreprocessing.so | Intel Audio HAL Effects Pre-Processing | (?) | *Missing on AOSP-only*

That should be it.
Need some advice on the ones I don't know what to do, @tank0412 @quanganh2627.

**Comment by dgadelha** [comment]
## Extra Files Missing from Stock .87
```
lib/liblocSDK5.so
lib/libthermalJNI.so
lib/plugins/libart-extension.so
vendor/etc/audio_effects.conf
vendor/etc/fallback_fonts.xml
```

Library | Description | Needed? | Notes
--------|-------------|---------|------
liblocSDK5.so | Baidu Location SDK v5 | No | *N/A*
libthermalJNI.so | Intel ituxd Thermal JNI Library | No | *N/A*
plugins/libart-extension.so | Intel x86 ART Extension | (?) | The device files contain a line to build this file, but it isn't built (should we use a prebuilt?)

I don't think we also need the files
```
vendor/etc/audio_effects.conf
vendor/etc/fallback_fonts.xml
```

[Entire List Available Here - CM12.1](https://github.com/zf5/android_vendor_asus_a500cg/files/181166/missing.txt)
[Entire List Available Here - AOSP](https://github.com/zf5/android_vendor_asus_a500cg/files/181167/missing-aosp.txt)

**Comment by tank0412** [comment]
https://drive.google.com/file/d/0B-Fin8UxrD6PMnBrak9naGFLQU0/view?usp=sharing
It is a list of lib folder where all is OK. Audio, media is OK. Buttons is OK too.

**Comment by dgadelha** [comment]
@tank0412 the missing files are only these:
```
libAFE.so
libBaiduMapSDK_v2_4_1.so
libPdfConverter.so
libSTC.so
libcctapi.so
libcurve25519-old.so
libfilterpack_facedetect.so
libjSebring.so
libjUPnPCP.so
libjni_xt9input.so
libkeyboard_jni.so
libmllite.so
libmorpho_panorama_gp.so
libmplmpu.so
libnatnl-1.7.11.2.so
libola.so
libsarcsoft_gallery.so
libsarcsoftface.so
libsmartdialer_oem_module.so
libsmartdialernet_oem_module.so
libsphere.so
libsphere2.so
libsphere3.so
libstlport_shared.so
libstrokenumjni.so
libsvml.so
libtrendmicro_jni.so
libwatchdogd_devel.so
soundfx/liblpepreprocessing.so
```
And they are the ones mentioned at https://github.com/zf5/android_vendor_asus_a500cg/issues/1#issuecomment-198844533
I just need that you take a look on the table and possibly send a update with a Yes or No on some of the **(?)**'s

**Comment by dgadelha** [comment]
## Update
Library | Description | Needed? | Notes
--------|-------------|---------|------
plugins/libart-extension.so | Intel x86 ART Extension | Yes | *N/A*
libcctapi.so | ASUS Kernel Management API | Yes | *N/A*
libstlport_shared.so | STLPort Shared Library | Yes | *TODO: Check if we can build this*

**Comment by dgadelha** [comment]
After using the @quanganh2627 files, something curious has happened.
Stagefright now depends on the libsvml.so, and it didn't before
```
E/MDP_OMX_CORE(  232): unable to dlopen libstagefright_soft_mp3dec_mdp.so: dlopen failed: library "libsvml.so" not found
```
Altough, after adding the library file, a new error happens:
```
E/MDP_OMX_CORE(  232): unable to dlopen libstagefright_soft_mp3dec_mdp.so: dlopen failed: cannot locate symbol "ippsZero_16s" referenced by "libstagefright_soft_mp3dec_mdp.so"...
```
After cd'ing to the libraries folder and running `grep -R "ippsZero_16s" .`, we see
```
Binary file ./libstagefright_soft_aacenc_mdp.so matches
Binary file ./libstagefright_soft_aacdec_mdp.so matches
Binary file ./libwidimedia.so matches
Binary file ./libstagefright_soft_amrenc_mdp.so matches
Binary file ./libstagefright_soft_mp3dec_mdp.so matches
Binary file ./libstagefright_soft_amrdec_mdp.so matches
Binary file ./libstagefright_soft_wmadec_mdp.so matches
```
Replacing all those libraries isn't enough, the system still not booting.

I'm testing yet. If I fail, https://github.com/zf5/android_vendor_asus_a500cg/commit/00f899d72925e999c2ae98464ae9f58d9fa42c47 should be reverted.

**Comment by dgadelha** [comment]
That should be enough.

**Comment by quanganh2627** [comment]
Wow, it's look like you spend a ton of your time, right? For ippsZero...., it's exactly a static named libipps, including in intel src tree which I usually suggested all of you should download it. I was trying to uploaded it to github but github drop it due to its size(>100mb , overload github upload limited). for libart-plugins, I'm not sure but hoping it would, because like intel's mentioned it support optimizing for libart.

**Comment by dgadelha** [comment]
Yes, I'm trying to find out how to fix the Bluetooth Audio and Random Screen Locks.
Also, where do you get that Intel SRC Tree?

**Comment by quanganh2627** [comment]
Goto http://pages.path.windriver.com/android_bay_trail_eval, fill in their form, then they will send you email contains link to download from their ftp server. Newer than that, there is a newer address and src is go to ami.com, but requires you have a company email domain, not a free popular like @google.com or @yahoo.com.....It's too complicate for freelance development working on open src. One big stupid, then minus one point for intel, isn't it?

**Comment by dgadelha** [comment]
But we can't share it if we use it:
`(a) Customer may not disclose, distribute or transfer any part of the Software except as provided in this Agreement, and customer agree to prevent unauthorized copying of the Software.`
